// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/duck/v1alpha1"
)

// FakeUpgradableTypes implements UpgradableTypeInterface
type FakeUpgradableTypes struct {
	Fake *FakeDuckV1alpha1
}

var upgradabletypesResource = schema.GroupVersionResource{Group: "duck.open-cluster-management.io", Version: "v1alpha1", Resource: "upgradabletypes"}

var upgradabletypesKind = schema.GroupVersionKind{Group: "duck.open-cluster-management.io", Version: "v1alpha1", Kind: "UpgradableType"}

// Get takes name of the upgradableType, and returns the corresponding upgradableType object, and an error if there is any.
func (c *FakeUpgradableTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UpgradableType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(upgradabletypesResource, name), &v1alpha1.UpgradableType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpgradableType), err
}

// List takes label and field selectors, and returns the list of UpgradableTypes that match those selectors.
func (c *FakeUpgradableTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UpgradableTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(upgradabletypesResource, upgradabletypesKind, opts), &v1alpha1.UpgradableTypeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UpgradableTypeList{ListMeta: obj.(*v1alpha1.UpgradableTypeList).ListMeta}
	for _, item := range obj.(*v1alpha1.UpgradableTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested upgradableTypes.
func (c *FakeUpgradableTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(upgradabletypesResource, opts))
}

// Create takes the representation of a upgradableType and creates it.  Returns the server's representation of the upgradableType, and an error, if there is any.
func (c *FakeUpgradableTypes) Create(ctx context.Context, upgradableType *v1alpha1.UpgradableType, opts v1.CreateOptions) (result *v1alpha1.UpgradableType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(upgradabletypesResource, upgradableType), &v1alpha1.UpgradableType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpgradableType), err
}

// Update takes the representation of a upgradableType and updates it. Returns the server's representation of the upgradableType, and an error, if there is any.
func (c *FakeUpgradableTypes) Update(ctx context.Context, upgradableType *v1alpha1.UpgradableType, opts v1.UpdateOptions) (result *v1alpha1.UpgradableType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(upgradabletypesResource, upgradableType), &v1alpha1.UpgradableType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpgradableType), err
}

// Delete takes name of the upgradableType and deletes it. Returns an error if one occurs.
func (c *FakeUpgradableTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(upgradabletypesResource, name, opts), &v1alpha1.UpgradableType{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUpgradableTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(upgradabletypesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UpgradableTypeList{})
	return err
}

// Patch applies the patch and returns the patched upgradableType.
func (c *FakeUpgradableTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpgradableType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(upgradabletypesResource, name, pt, data, subresources...), &v1alpha1.UpgradableType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpgradableType), err
}
