// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/client/duck/clientset/versioned/typed/duck/v1alpha1"
)

type FakeDuckV1alpha1 struct {
	*testing.Fake
}

func (c *FakeDuckV1alpha1) UpgradableTypes() v1alpha1.UpgradableTypeInterface {
	return &FakeUpgradableTypes{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDuckV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
