apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustermanagementaddons.addon.open-cluster-management.io
spec:
  group: addon.open-cluster-management.io
  names:
    kind: ClusterManagementAddOn
    listKind: ClusterManagementAddOnList
    plural: clustermanagementaddons
    singular: clustermanagementaddon
  scope: Cluster
  preserveUnknownFields: false
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.addOnMeta.displayName
          name: DISPLAY NAME
          type: string
        - jsonPath: .spec.addOnConfiguration.crdName
          name: CRD NAME
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: ClusterManagementAddOn represents the registration of an add-on to the cluster manager. This resource allows the user to discover which add-on is available for the cluster manager and also provides metadata information about the add-on. This resource also provides a linkage to ManagedClusterAddOn, the name of the ClusterManagementAddOn resource will be used for the namespace-scoped ManagedClusterAddOn resource. ClusterManagementAddOn is a cluster-scoped resource.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: spec represents a desired configuration for the agent on the cluster management add-on.
              type: object
              properties:
                addOnConfiguration:
                  description: 'Deprecated: Use supportedConfigs filed instead addOnConfiguration is a reference to configuration information for the add-on. In scenario where a multiple add-ons share the same add-on CRD, multiple ClusterManagementAddOn resources need to be created and reference the same AddOnConfiguration.'
                  type: object
                  properties:
                    crName:
                      description: crName is the name of the CR used to configure instances of the managed add-on. This field should be configured if add-on CR have a consistent name across the all of the ManagedCluster instaces.
                      type: string
                    crdName:
                      description: crdName is the name of the CRD used to configure instances of the managed add-on. This field should be configured if the add-on have a CRD that controls the configuration of the add-on.
                      type: string
                    lastObservedGeneration:
                      description: lastObservedGeneration is the observed generation of the custom resource for the configuration of the addon.
                      type: integer
                      format: int64
                addOnMeta:
                  description: addOnMeta is a reference to the metadata information for the add-on.
                  type: object
                  properties:
                    description:
                      description: description represents the detailed description of the add-on.
                      type: string
                    displayName:
                      description: displayName represents the name of add-on that will be displayed.
                      type: string
                configuration:
                  description: configuration lists the add-on configurations and the rollout strategy when the configurations change.
                  type: object
                  properties:
                    configs:
                      description: configs is a list of add-on configurations. The add-on configurations for each cluster can be overridden by the configs of the ManagedClusterAddon spec.
                      type: array
                      items:
                        type: object
                        required:
                          - name
                          - resource
                        properties:
                          group:
                            description: group of the add-on configuration.
                            type: string
                            default: ""
                          name:
                            description: name of the add-on configuration.
                            type: string
                            minLength: 1
                          namespace:
                            description: namespace of the add-on configuration. If this field is not set, the configuration is in the cluster scope.
                            type: string
                          resource:
                            description: resource of the add-on configuration.
                            type: string
                            minLength: 1
                    rolloutStrategy:
                      description: The rollout strategy to apply new configs. The rollout strategy only watches the listed configs change. If the rollout strategy is not defined, the default strategy UpdateAll is used. If there are configs change during the rollout process, the rollout will start over. For example, configs list configA and configB. The change in configA triggers the rollout. If the configB is also changed before the rollout is complete, the current rollout stops and the rollout starts over.
                      type: object
                      properties:
                        rollingUpdateWithPlacement:
                          description: Rolling update with placement config params. Present only if the type is RollingUpdateWithPlacement.
                          type: object
                          required:
                            - name
                            - namespace
                          properties:
                            maxConcurrentlyUpdating:
                              description: 'The maximum concurrently updating number of addons. Value can be an absolute number (ex: 5) or a percentage of desired addons (ex: 10%). Absolute number is calculated from percentage by rounding up. Defaults to 25%. Example: when this is set to 30%, once the addon configs change, the addon on 30% of the selected clusters will adopt the new configs. When the new configs are ready, the addon on the remaining clusters will be further updated.'
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            name:
                              description: name of the placement
                              type: string
                            namespace:
                              description: namespace of the placement.
                              type: string
                        type:
                          description: 'Type is the type of the rollout strategy, it supports UpdateAll and RollingUpdateWithPlacement: - UpdateAll: when configs change, apply the new configs to all the clusters. - RollingUpdateWithPlacement: when configs change, rolling update new configs on the clusters   selected by placements.   If any of the configs are overridden by ManagedClusterAddOn on the specific cluster, the new configs   won''t take effect on that cluster.   This rollout strategy is only responsible for applying new configs. When the strategy is modified or   removed, the applied configs won''t be deleted from the cluster.'
                          type: string
                          default: UpdateAll
                          enum:
                            - RollingUpdateWithPlacement
                            - UpdateAll
                supportedConfigs:
                  description: 'Deprecated: move supportedConfigs to ManagedClusterAddOnStatus. supportedConfigs is a list of configuration types supported by add-on. An empty list means the add-on does not require configurations. The default is an empty list'
                  type: array
                  items:
                    description: ConfigMeta represents a collection of metadata information for add-on configuration.
                    type: object
                    required:
                      - resource
                    properties:
                      defaultConfig:
                        description: defaultConfig represents the namespace and name of the default add-on configuration. In scenario where all add-ons have a same configuration.
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            description: name of the add-on configuration.
                            type: string
                            minLength: 1
                          namespace:
                            description: namespace of the add-on configuration. If this field is not set, the configuration is in the cluster scope.
                            type: string
                      group:
                        description: group of the add-on configuration.
                        type: string
                        default: ""
                      resource:
                        description: resource of the add-on configuration.
                        type: string
                        minLength: 1
                  x-kubernetes-list-map-keys:
                    - group
                    - resource
                  x-kubernetes-list-type: map
            status:
              description: status represents the current status of cluster management add-on.
              type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
