// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "open-cluster-management.io/api/client/duck/clientset/versioned/scheme"
	v1alpha1 "open-cluster-management.io/api/duck/v1alpha1"
)

// UpgradableTypesGetter has a method to return a UpgradableTypeInterface.
// A group's client should implement this interface.
type UpgradableTypesGetter interface {
	UpgradableTypes(namespace string) UpgradableTypeInterface
}

// UpgradableTypeInterface has methods to work with UpgradableType resources.
type UpgradableTypeInterface interface {
	Create(ctx context.Context, upgradableType *v1alpha1.UpgradableType, opts v1.CreateOptions) (*v1alpha1.UpgradableType, error)
	Update(ctx context.Context, upgradableType *v1alpha1.UpgradableType, opts v1.UpdateOptions) (*v1alpha1.UpgradableType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.UpgradableType, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UpgradableTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpgradableType, err error)
	UpgradableTypeExpansion
}

// upgradableTypes implements UpgradableTypeInterface
type upgradableTypes struct {
	client rest.Interface
	ns     string
}

// newUpgradableTypes returns a UpgradableTypes
func newUpgradableTypes(c *DuckV1alpha1Client, namespace string) *upgradableTypes {
	return &upgradableTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the upgradableType, and returns the corresponding upgradableType object, and an error if there is any.
func (c *upgradableTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UpgradableType, err error) {
	result = &v1alpha1.UpgradableType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("upgradabletypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UpgradableTypes that match those selectors.
func (c *upgradableTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UpgradableTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UpgradableTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("upgradabletypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested upgradableTypes.
func (c *upgradableTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("upgradabletypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a upgradableType and creates it.  Returns the server's representation of the upgradableType, and an error, if there is any.
func (c *upgradableTypes) Create(ctx context.Context, upgradableType *v1alpha1.UpgradableType, opts v1.CreateOptions) (result *v1alpha1.UpgradableType, err error) {
	result = &v1alpha1.UpgradableType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("upgradabletypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(upgradableType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a upgradableType and updates it. Returns the server's representation of the upgradableType, and an error, if there is any.
func (c *upgradableTypes) Update(ctx context.Context, upgradableType *v1alpha1.UpgradableType, opts v1.UpdateOptions) (result *v1alpha1.UpgradableType, err error) {
	result = &v1alpha1.UpgradableType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("upgradabletypes").
		Name(upgradableType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(upgradableType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the upgradableType and deletes it. Returns an error if one occurs.
func (c *upgradableTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("upgradabletypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *upgradableTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("upgradabletypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched upgradableType.
func (c *upgradableTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpgradableType, err error) {
	result = &v1alpha1.UpgradableType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("upgradabletypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
