//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MandatoryDecisionGroup) DeepCopyInto(out *MandatoryDecisionGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MandatoryDecisionGroup.
func (in *MandatoryDecisionGroup) DeepCopy() *MandatoryDecisionGroup {
	if in == nil {
		return nil
	}
	out := new(MandatoryDecisionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRef) DeepCopyInto(out *PlacementRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRef.
func (in *PlacementRef) DeepCopy() *PlacementRef {
	if in == nil {
		return nil
	}
	out := new(PlacementRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRefs) DeepCopyInto(out *PlacementRefs) {
	*out = *in
	out.PlacementRef = in.PlacementRef
	in.RolloutStrategy.DeepCopyInto(&out.RolloutStrategy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRefs.
func (in *PlacementRefs) DeepCopy() *PlacementRefs {
	if in == nil {
		return nil
	}
	out := new(PlacementRefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStrategy) DeepCopyInto(out *RolloutStrategy) {
	*out = *in
	if in.MandatoryDecisionGroups != nil {
		in, out := &in.MandatoryDecisionGroups, &out.MandatoryDecisionGroups
		*out = make([]MandatoryDecisionGroup, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStrategy.
func (in *RolloutStrategy) DeepCopy() *RolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Upgradable) DeepCopyInto(out *Upgradable) {
	{
		in := &in
		*out = make(Upgradable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upgradable.
func (in Upgradable) DeepCopy() Upgradable {
	if in == nil {
		return nil
	}
	out := new(Upgradable)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradableSpec) DeepCopyInto(out *UpgradableSpec) {
	*out = *in
	if in.PlacementRefs != nil {
		in, out := &in.PlacementRefs, &out.PlacementRefs
		*out = make(Upgradable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradableSpec.
func (in *UpgradableSpec) DeepCopy() *UpgradableSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradableType) DeepCopyInto(out *UpgradableType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradableType.
func (in *UpgradableType) DeepCopy() *UpgradableType {
	if in == nil {
		return nil
	}
	out := new(UpgradableType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradableType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradableTypeList) DeepCopyInto(out *UpgradableTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradableType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradableTypeList.
func (in *UpgradableTypeList) DeepCopy() *UpgradableTypeList {
	if in == nil {
		return nil
	}
	out := new(UpgradableTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradableTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
