// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// UpgradableTypeListerExpansion allows custom methods to be added to
// UpgradableTypeLister.
type UpgradableTypeListerExpansion interface{}
