// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "open-cluster-management.io/api/duck/v1alpha1"
)

// UpgradableTypeLister helps list UpgradableTypes.
// All objects returned here must be treated as read-only.
type UpgradableTypeLister interface {
	// List lists all UpgradableTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.UpgradableType, err error)
	// UpgradableTypes returns an object that can list and get UpgradableTypes.
	UpgradableTypes(namespace string) UpgradableTypeNamespaceLister
	UpgradableTypeListerExpansion
}

// upgradableTypeLister implements the UpgradableTypeLister interface.
type upgradableTypeLister struct {
	indexer cache.Indexer
}

// NewUpgradableTypeLister returns a new UpgradableTypeLister.
func NewUpgradableTypeLister(indexer cache.Indexer) UpgradableTypeLister {
	return &upgradableTypeLister{indexer: indexer}
}

// List lists all UpgradableTypes in the indexer.
func (s *upgradableTypeLister) List(selector labels.Selector) (ret []*v1alpha1.UpgradableType, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.UpgradableType))
	})
	return ret, err
}

// UpgradableTypes returns an object that can list and get UpgradableTypes.
func (s *upgradableTypeLister) UpgradableTypes(namespace string) UpgradableTypeNamespaceLister {
	return upgradableTypeNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// UpgradableTypeNamespaceLister helps list and get UpgradableTypes.
// All objects returned here must be treated as read-only.
type UpgradableTypeNamespaceLister interface {
	// List lists all UpgradableTypes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.UpgradableType, err error)
	// Get retrieves the UpgradableType from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.UpgradableType, error)
	UpgradableTypeNamespaceListerExpansion
}

// upgradableTypeNamespaceLister implements the UpgradableTypeNamespaceLister
// interface.
type upgradableTypeNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all UpgradableTypes in the indexer for a given namespace.
func (s upgradableTypeNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.UpgradableType, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.UpgradableType))
	})
	return ret, err
}

// Get retrieves the UpgradableType from the indexer for a given namespace and name.
func (s upgradableTypeNamespaceLister) Get(name string) (*v1alpha1.UpgradableType, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("upgradabletype"), name)
	}
	return obj.(*v1alpha1.UpgradableType), nil
}
