// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "open-cluster-management.io/api/client/duck/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// UpgradableTypes returns a UpgradableTypeInformer.
	UpgradableTypes() UpgradableTypeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// UpgradableTypes returns a UpgradableTypeInformer.
func (v *version) UpgradableTypes() UpgradableTypeInformer {
	return &upgradableTypeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
