// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "open-cluster-management.io/api/client/duck/clientset/versioned"
	internalinterfaces "open-cluster-management.io/api/client/duck/informers/externalversions/internalinterfaces"
	v1alpha1 "open-cluster-management.io/api/client/duck/listers/duck/v1alpha1"
	duckv1alpha1 "open-cluster-management.io/api/duck/v1alpha1"
)

// UpgradableTypeInformer provides access to a shared informer and lister for
// UpgradableTypes.
type UpgradableTypeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.UpgradableTypeLister
}

type upgradableTypeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewUpgradableTypeInformer constructs a new informer for UpgradableType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUpgradableTypeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUpgradableTypeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredUpgradableTypeInformer constructs a new informer for UpgradableType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUpgradableTypeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().UpgradableTypes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().UpgradableTypes(namespace).Watch(context.TODO(), options)
			},
		},
		&duckv1alpha1.UpgradableType{},
		resyncPeriod,
		indexers,
	)
}

func (f *upgradableTypeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUpgradableTypeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *upgradableTypeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&duckv1alpha1.UpgradableType{}, f.defaultInformer)
}

func (f *upgradableTypeInformer) Lister() v1alpha1.UpgradableTypeLister {
	return v1alpha1.NewUpgradableTypeLister(f.Informer().GetIndexer())
}
